
import React, { useMemo, useState } from 'react';
import { DailyProgram, Flight, Staff, ShiftConfig, LeaveRequest, IncomingDuty, Assignment, Skill } from '../types';
import { calculateCredits } from '../services/geminiService';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  Printer, 
  Activity,
  CheckCircle2,
  FileText
} from 'lucide-react';
import { AVAILABLE_SKILLS } from '../constants';

interface Props {
  programs: DailyProgram[];
  flights: Flight[];
  staff: Staff[];
  shifts: ShiftConfig[];
  leaveRequests?: LeaveRequest[];
  incomingDuties?: IncomingDuty[];
  startDate?: string;
  endDate?: string;
  onUpdatePrograms?: (updatedPrograms: DailyProgram[]) => void;
  stationHealth?: number;
  alerts?: { type: 'danger' | 'warning', message: string }[];
  minRestHours?: number;
}

export const ProgramDisplay: React.FC<Props> = ({ 
  programs, 
  flights, 
  staff, 
  shifts, 
  leaveRequests = [], 
  incomingDuties = [], 
  startDate, 
  endDate, 
  minRestHours = 12
}) => {
  const [attachAnalytics, setAttachAnalytics] = useState(true);

  const filteredPrograms = useMemo(() => {
    if (!Array.isArray(programs) || !startDate || !endDate) return [];
    return [...programs]
      .filter(p => p.dateString && p.dateString >= startDate && p.dateString <= endDate)
      .sort((a, b) => (a.dateString || '').localeCompare(b.dateString || ''));
  }, [programs, startDate, endDate]);

  const getStaffById = (id: string) => staff.find(s => s.id === id);
  const getFlightById = (id: string) => flights.find(f => f.id === id);

  const getShiftDuration = (shift?: ShiftConfig) => {
    if (!shift) return "0.0";
    const [h1, m1] = shift.pickupTime.split(':').map(Number);
    const [h2, m2] = shift.endTime.split(':').map(Number);
    let start = h1 * 60 + (m1 || 0);
    let end = h2 * 60 + (m2 || 0);
    if (end < start) end += 1440;
    return ((end - start) / 60).toFixed(1);
  };

  const getFormatDate = (dateStr?: string) => {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'numeric', year: 'numeric' }).toUpperCase().replace(',', ' -');
  };

  const getSkillCodeShort = (role: string) => {
    if (role.includes('Leader')) return 'SL';
    if (role.includes('Load')) return 'LC';
    if (role.includes('Ramp')) return 'RMP';
    if (role.includes('Ops')) return 'OPS';
    if (role.includes('Lost')) return 'LF';
    return role;
  };

  const stats = useMemo(() => {
    if (!startDate || !endDate) return null;
    const duration = filteredPrograms.length;
    let totalSupply = 0;
    let totalDemand = 0;
    
    const roleStats = AVAILABLE_SKILLS.map(skill => {
        let sCount = 0;
        let dCount = 0;
        staff.forEach(s => {
            const hasSkill = (skill === 'Shift Leader' && s.isShiftLeader) || (skill === 'Load Control' && s.isLoadControl) || (skill === 'Ramp' && s.isRamp) || (skill === 'Operations' && s.isOps) || (skill === 'Lost and Found' && s.isLostFound);
            if (hasSkill) sCount += calculateCredits(s, startDate, duration, leaveRequests);
        });
        shifts.filter(s => s.pickupDate >= startDate && s.pickupDate <= endDate).forEach(s => {
            dCount += (s.roleCounts?.[skill] || 0);
        });
        return { skill, supply: sCount, demand: dCount };
    });

    staff.forEach(s => totalSupply += calculateCredits(s, startDate, duration, leaveRequests));
    shifts.filter(s => s.pickupDate >= startDate && s.pickupDate <= endDate).forEach(s => totalDemand += s.minStaff);
    
    return { totalSupply, totalDemand, balance: totalSupply - totalDemand, status: (totalSupply - totalDemand) >= 0 ? 'HEALTHY' : 'CRITICAL', roleStats };
  }, [startDate, endDate, staff, shifts, leaveRequests, filteredPrograms]);

  const generatePDF = () => {
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const drawHeader = (title: string, isCover: boolean = false) => {
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, pageWidth, 40, 'F');
      doc.setFontSize(26);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.text("SkyOPS EXECUTIVE STATION PROGRAM", 14, 20);
      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184);
      doc.text(`Operational Period: ${startDate} to ${endDate} | Generated by AI Intelligence Engine`, 14, 30);
      
      if (isCover && stats) {
        const bx = pageWidth - 94;
        doc.setFillColor(255, 255, 255);
        doc.setDrawColor(226, 232, 240);
        doc.rect(bx, 8, 80, 24, 'FD');
        doc.setFontSize(8);
        doc.setTextColor(0, 0, 0);
        doc.text("CAPACITY KPI SUMMARY", bx + 5, 14);
        doc.setFontSize(7);
        doc.text(`Gross Supply: ${stats.totalSupply} SHT`, bx + 5, 19);
        doc.text(`Net Balance: ${stats.balance > 0 ? '+' : ''}${stats.balance}`, bx + 5, 24);
        doc.setTextColor(16, 185, 129);
        doc.text(`Status: ${stats.status}`, bx + 45, 24);
      }

      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.text(title, 14, 55);
    };

    // 1. Handling Pages
    filteredPrograms.forEach((p, idx) => {
      if (idx > 0) doc.addPage();
      drawHeader(getFormatDate(p.dateString), idx === 0);

      const dayShifts = shifts.filter(s => s.pickupDate === p.dateString).sort((a,b) => a.pickupTime.localeCompare(b.pickupTime));
      const body = dayShifts.map((s, si) => {
        const assigned = p.assignments.filter(a => a.shiftId === s.id);
        const flts = (s.flightIds || []).map(fid => getFlightById(fid)?.flightNumber).filter(Boolean).join(', ') || 'NIL';
        const prs = assigned.map(a => `${getStaffById(a.staffId)?.initials} (${getSkillCodeShort(a.role)})`).join(' | ');
        return [si + 1, s.pickupTime, s.endTime, flts, `${assigned.length}/${s.maxStaff}`, prs];
      });

      autoTable(doc, {
        startY: 65,
        head: [['S/N', 'ON-DUTY', 'OFF-DUTY', 'FLIGHTS', 'HC', 'PERSONNEL & ROLES']],
        body,
        theme: 'grid',
        headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255], fontSize: 8 },
        styles: { fontSize: 7, cellPadding: 2 },
        columnStyles: { 0: { cellWidth: 10 }, 4: { cellWidth: 15 }, 5: { cellWidth: 'auto' } }
      });

      // ABSENCE REGISTRY FOOTER
      const footerY = pageHeight - 50;
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text("DAILY ABSENCE & REST REGISTRY", 14, footerY);
      
      const dayLeaves = leaveRequests.filter(l => l.startDate <= p.dateString! && l.endDate >= p.dateString!);
      const dayAssignments = p.assignments.map(a => a.staffId);
      const dayOffRosters = staff.filter(s => s.type === 'Roster' && !dayAssignments.includes(s.id) && s.workFromDate && s.workToDate && p.dateString! >= s.workFromDate && p.dateString! <= s.workToDate);
      
      const regBody = [
        ['OFF-DUTY (DAYS OFF)', dayLeaves.filter(l => l.type === 'Day off').map(l => getStaffById(l.staffId)?.initials).join(', ') || 'NONE'],
        ['CONTRACTED REST (ROSTER)', dayOffRosters.map(r => r.initials).join(', ') || 'NONE'],
        ['ANNUAL LEAVE', dayLeaves.filter(l => l.type === 'Annual leave').map(l => getStaffById(l.staffId)?.initials).join(', ') || 'NONE'],
        ['OUT OF CONTRACT', staff.filter(s => s.type === 'Roster' && (p.dateString! < (s.workFromDate||'') || p.dateString! > (s.workToDate||''))).map(s => s.initials).join(', ') || 'NONE']
      ];

      autoTable(doc, {
        startY: footerY + 4,
        head: [['STATUS CATEGORY', 'PERSONNEL INITIALS']],
        body: regBody,
        theme: 'grid',
        headStyles: { fillColor: [71, 85, 105], fontSize: 8 },
        styles: { fontSize: 7, cellPadding: 2 },
        columnStyles: { 0: { cellWidth: 50 } }
      });
    });

    if (attachAnalytics) {
      // 2. Full Manpower Statistics Registry
      doc.addPage();
      drawHeader("STATION MANPOWER STATUS REGISTRY");
      const staffRows = staff.map((s, i) => {
        const potential = calculateCredits(s, startDate!, filteredPrograms.length, []);
        const actual = programs.reduce((acc, p) => acc + p.assignments.filter(a => a.staffId === s.id).length, 0);
        const status = actual > potential ? 'OVERWORK' : (actual === potential ? 'MATCH' : 'SURPLUS');
        return [i + 1, s.name, s.initials, s.type, s.type === 'Local' ? 'Permanent' : `${s.workFromDate} > ${s.workToDate}`, potential, actual, status];
      });
      autoTable(doc, {
        startY: 65,
        head: [['S/N', 'NAME', 'INIT', 'TYPE', 'CONTRACT WINDOW', 'CAP', 'ACT', 'AUDIT']],
        body: staffRows,
        theme: 'striped',
        headStyles: { fillColor: [15, 23, 42] },
        styles: { fontSize: 7 },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 7) {
            const val = data.cell.text[0];
            if (val === 'OVERWORK') data.cell.styles.textColor = [225, 29, 72];
            if (val === 'MATCH') data.cell.styles.textColor = [16, 185, 129];
            data.cell.styles.fontStyle = 'bold';
          }
        }
      });

      // 3. Specialist Fulfillment matrix
      doc.addPage();
      drawHeader("SPECIALIST DISCIPLINE MATRIX");
      const matrixHead = [['DATE', 'SHIFT', 'SL (LEAD)', 'LC (LOAD)', 'RMP (RAMP)', 'OPS (OPS)', 'LF (LOST)']];
      const matrixBody: any[] = [];
      filteredPrograms.forEach(p => {
        shifts.filter(s => s.pickupDate === p.dateString).forEach(s => {
            const assigned = p.assignments.filter(a => a.shiftId === s.id);
            const getP = (skill: string) => assigned.filter(a => a.role.includes(getSkillCodeShort(skill))).map(a => getStaffById(a.staffId)?.initials).join(', ') || '-';
            matrixBody.push([p.dateString, `${s.pickupTime}-${s.endTime}`, getP('Shift Leader'), getP('Load Control'), getP('Ramp'), getP('Operations'), getP('Lost and Found')]);
        });
      });
      autoTable(doc, {
        startY: 65,
        head: matrixHead,
        body: matrixBody,
        theme: 'grid',
        headStyles: { fillColor: [37, 99, 235] },
        styles: { fontSize: 6, fontStyle: 'bold' }
      });
    }

    doc.save(`SkyOPS_Handling_Program_${startDate}.pdf`);
  };

  return (
    <div className="space-y-8 pb-32 animate-in fade-in duration-500">
      <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-slate-100 flex flex-col md:flex-row justify-between items-center gap-6">
        <div>
           <h2 className="text-3xl font-black italic uppercase text-slate-900 tracking-tighter">Operational Analytics</h2>
           <p className="text-xs font-black text-slate-400 uppercase tracking-widest mt-2 flex items-center gap-2">
             <Activity size={14} className="text-blue-500" /> Executive Program Publisher
           </p>
           <label className="flex items-center gap-3 mt-4 cursor-pointer group">
              <input type="checkbox" className="w-5 h-5 rounded border-slate-200" checked={attachAnalytics} onChange={e => setAttachAnalytics(e.target.checked)} />
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-600 group-hover:text-slate-900">Attach Station Intelligence Report (Full PDF)</span>
           </label>
        </div>
        <button onClick={generatePDF} className="px-10 py-5 bg-slate-950 text-white rounded-2xl text-[10px] font-black uppercase flex items-center gap-3 shadow-xl hover:bg-blue-600 transition-all active:scale-95">
           <Printer size={18} /> Issue Final Program
        </button>
      </div>

      <div className="bg-white rounded-[2.5rem] shadow-sm border border-slate-100 overflow-hidden">
        <div className="p-8 md:p-12 space-y-12">
            {stats && (
              <div className="flex justify-end">
                <div className="bg-slate-50 p-8 rounded-2xl border border-slate-200 shadow-sm w-full max-w-md">
                   <h4 className="text-xs font-black text-slate-950 uppercase tracking-widest border-b border-slate-100 pb-3 mb-4">Production Audit</h4>
                   <div className="space-y-2 text-[11px] font-medium text-slate-600">
                      <p>Active Supply: <span className="font-black text-slate-950">{stats.totalSupply} Shifts</span></p>
                      <p>Station Demand: <span className="font-black text-slate-950">{stats.totalDemand} Shifts</span></p>
                      <div className="pt-4 flex justify-between items-center">
                         <span className="text-emerald-500 font-black italic">NET BALANCE: {stats.balance > 0 ? '+' : ''}{stats.balance}</span>
                         <span className={`px-3 py-1 rounded-lg text-[9px] font-black uppercase ${stats.balance >= 0 ? 'bg-emerald-100 text-emerald-600' : 'bg-rose-100 text-rose-600 animate-pulse'}`}>{stats.status}</span>
                      </div>
                   </div>
                </div>
              </div>
            )}

            {filteredPrograms.map((p) => {
              const dayShifts = shifts.filter(s => s.pickupDate === p.dateString).sort((a,b) => a.pickupTime.localeCompare(b.pickupTime));
              return (
                <div key={p.dateString} className="space-y-6">
                  <h3 className="text-2xl font-black italic text-slate-900 uppercase tracking-tight flex items-center gap-3">
                     <FileText className="text-blue-600" /> {getFormatDate(p.dateString)}
                  </h3>
                  <div className="overflow-x-auto border border-slate-100 rounded-2xl">
                    <table className="w-full text-left border-collapse">
                       <thead className="bg-black text-white text-[10px] font-black uppercase tracking-widest">
                         <tr>
                           <th className="p-4">S/N</th>
                           <th className="p-4">ON-DUTY</th>
                           <th className="p-4">OFF-DUTY</th>
                           <th className="p-4">FLIGHTS</th>
                           <th className="p-4">HC</th>
                           <th className="p-4">PERSONNEL REGISTRY</th>
                         </tr>
                       </thead>
                       <tbody className="divide-y divide-slate-100 text-[11px]">
                          {dayShifts.map((s, si) => {
                            const assigned = p.assignments.filter(a => a.shiftId === s.id);
                            return (
                              <tr key={s.id} className="hover:bg-slate-50 transition-colors">
                                <td className="p-4 font-bold text-slate-400">{si + 1}</td>
                                <td className="p-4 font-black text-slate-900">{s.pickupTime}</td>
                                <td className="p-4 font-black text-slate-900">{s.endTime}</td>
                                <td className="p-4">
                                  <div className="flex flex-wrap gap-1">
                                    {(s.flightIds || []).map(fid => (
                                      <span key={fid} className="px-1.5 py-0.5 bg-slate-100 rounded text-[9px] font-black uppercase">{getFlightById(fid)?.flightNumber}</span>
                                    )) || 'NIL'}
                                  </div>
                                </td>
                                <td className="p-4 font-black text-slate-600">{assigned.length}/{s.maxStaff}</td>
                                <td className="p-4">
                                   <div className="flex flex-wrap gap-2 text-[10px]">
                                      {assigned.map(a => (
                                        <span key={a.id} className="text-slate-900 font-medium">
                                           {getStaffById(a.staffId)?.initials} ({getSkillCodeShort(a.role)})
                                           {si < dayShifts.length - 1 && <span className="mx-2 text-slate-200">|</span>}
                                        </span>
                                      ))}
                                   </div>
                                </td>
                              </tr>
                            );
                          })}
                       </tbody>
                    </table>
                  </div>
                </div>
              );
            })}
        </div>
      </div>
    </div>
  );
};
